name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "Publishing environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - production
      skip_tests:
        description: "Skip running tests"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run unit tests
        run: pytest -m "not integration" -v

      - name: Run integration tests
        if: github.event_name == 'release'
        env:
          MXBAI_API_KEY: ${{ secrets.MXBAI_API_KEY }}
        run: pytest -m "integration" -v

  build:
    runs-on: ubuntu-latest
    needs: test
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-test:
    runs-on: ubuntu-latest
    needs: build
    if: |
      always() && 
      needs.build.result == 'success' && 
      (github.event_name == 'workflow_dispatch' && inputs.environment == 'test')
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/mixedbread-ai-langchain
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          verbose: true

  publish-production:
    runs-on: ubuntu-latest
    needs: build
    if: |
      always() && 
      needs.build.result == 'success' && 
      (github.event_name == 'release' || 
       (github.event_name == 'workflow_dispatch' && inputs.environment == 'production'))
    environment:
      name: pypi
      url: https://pypi.org/p/mixedbread-ai-langchain
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
